
package com.workday.incentivecalceligibleemployees;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportPort", targetNamespace = "urn:com.workday.report/Incentive__Input_Template_Report_-_BNL")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportPort {


    /**
     * 
     * @param reportParameters
     * @param authentication
     * @return
     *     returns java.util.List<com.workday.incentivecalceligibleemployees.ReportEntryType>
     */
    @WebMethod(operationName = "Execute_Report")
    @WebResult(name = "Report_Entry", targetNamespace = "urn:com.workday.report/Incentive__Input_Template_Report_-_BNL")
    @RequestWrapper(localName = "Execute_Report", targetNamespace = "urn:com.workday.report/Incentive__Input_Template_Report_-_BNL", className = "com.workday.incentivecalceligibleemployees.ExecuteReportType")
    @ResponseWrapper(localName = "Report_Data", targetNamespace = "urn:com.workday.report/Incentive__Input_Template_Report_-_BNL", className = "com.workday.incentivecalceligibleemployees.ReportDataType")
    public List<ReportEntryType> executeReport(
        @WebParam(name = "Report_Parameters", targetNamespace = "urn:com.workday.report/Incentive__Input_Template_Report_-_BNL")
        ReportParametersType reportParameters,
        @WebParam(name = "Authentication", targetNamespace = "urn:com.workday.report/Incentive__Input_Template_Report_-_BNL")
        AuthenticationType authentication);

}
